### ISSUE TITLE
I want use camb in ubuntu20 and python3.8 but I can not install with pip3 install camb. please help me.

### ISSUE THREAD

**Issue by Sara-Re-d** [cmbant/CAMB#101]
ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tf_vvgcs/camb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tf_vvgcs/camb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-q8i91lo6
       cwd: /tmp/pip-install-tf_vvgcs/camb/
  Complete output (35 lines):
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-tf_vvgcs/camb/setup.py", line 269, in <module>
      setup(name=os.getenv('CAMB_PACKAGE_NAME', 'camb'),
    File "/home/sara/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-tf_vvgcs/camb/setup.py", line 233, in run
      make_library(False)
    File "/tmp/pip-install-tf_vvgcs/camb/setup.py", line 111, in make_library
      ok, gfortran_version = _compile.check_gfortran(msg=not _compile.is_windows)
    File "/tmp/pip-install-tf_vvgcs/camb/camb/_compilers.py", line 71, in check_gfortran
      raise Exception(
  Exception: You need ifort or gfortran 6 or higher to compile (found: None).
  See https://camb.readthedocs.io/en/latest/fortran_compilers.html
  ----------------------------------------
  ERROR: Failed building wheel for camb
  Running setup.py clean for camb
Failed to build camb
Installing collected packages: camb
    Running setup.py install for camb ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tf_vvgcs/camb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tf_vvgcs/camb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8dgsiyow/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/sara/.local/include/python3.8/camb
         cwd: /tmp/pip-install-tf_vvgcs/camb/
    Complete output (37 lines):
    running install
    running build
    running build_py
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tf_vvgcs/camb/setup.py", line 269, in <module>
        setup(name=os.getenv('CAMB_PACKAGE_NAME', 'camb'),
      File "/home/sara/.local/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/sara/.local/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-tf_vvgcs/camb/setup.py", line 233, in run
        make_library(False)
      File "/tmp/pip-install-tf_vvgcs/camb/setup.py", line 111, in make_library
        ok, gfortran_version = _compile.check_gfortran(msg=not _compile.is_windows)
      File "/tmp/pip-install-tf_vvgcs/camb/camb/_compilers.py", line 71, in check_gfortran
        raise Exception(
    Exception: You need ifort or gfortran 6 or higher to compile (found: None).
    See https://camb.readthedocs.io/en/latest/fortran_compilers.html
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tf_vvgcs/camb/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tf_vvgcs/camb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-8dgsiyow/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/sara/.local/include/python3.8/camb Check the logs for full command output.

**Comment by cmbant** [comment]
Is the error message not correct?
