### ISSUE TITLE
Compiling camb on Mac with M1 chip and running from anaconda3 python

### ISSUE THREAD

**Issue by elykovetz** [cmbant/CAMB#103]
Hello,

I am encountering this issue:  

>>> import camb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/elymini/opt/anaconda3/lib/python3.8/site-packages/camb/__init__.py", line 12, in <module>
    from . import baseconfig
  File "/Users/elymini/opt/anaconda3/lib/python3.8/site-packages/camb/baseconfig.py", line 66, in <module>
    camblib = ctypes.LibraryLoader(IfortGfortranLoader).LoadLibrary(CAMBL)
  File "/Users/elymini/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/Users/elymini/opt/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/elymini/opt/anaconda3/lib/python3.8/site-packages/camb/camblib.so, 6): no suitable image found.  Did find:
	/Users/elymini/opt/anaconda3/lib/python3.8/site-packages/camb/camblib.so: mach-o, but wrong architecture
	/Users/elymini/opt/anaconda3/lib/python3.8/site-packages/camb/camblib.so: mach-o, but wrong architecture

Camb installed fine using pip install camb (after brew install gcc). Is there a fix for this?

Thanks!

**Comment by cmbant** [comment]
See e.g. https://stackoverflow.com/questions/39477023/error-mach-o-but-wrong-architecture-after-installing-anaconda-on-mac
You can try installing camb from conda-forge rather than pip, if your python is 64bit.
