### ISSUE TITLE
Typo in argument name crashes python kernel instead of throwing error.

### ISSUE THREAD

**Issue by SergeiDBykov** [cmbant/CAMB#110]
Hello and thanks for the great package!

I found that `camb` python wrapper possibly has problems with handling errors.

In the example below I use '`zarr`' instead of '`z`' as an argument for tracer (assume this is a simple typo).

```
import numpy as np
import camb
from camb.sources import GaussianSourceWindow, SplinedSourceWindow

z = np.linspace(0.5, 2, 100)


def gaussian(x, mu, sig):
    return np.exp(-np.power(x - mu, 2.) / (2 * np.power(sig, 2.)))


nz1 = gaussian(z, 1, 0.2)*50
nz2 = gaussian(z, 1.5, 0.2)*70
bias = 2*np.ones_like(z)


cp = camb.model.CAMBparams()
l_max = 50
cp.set_cosmology(H0=67.5, ombh2=0.022, omch2=0.122)

cp.SourceWindows = [SplinedSourceWindow(dlog10Ndm=0, z=z, W=nz1, bias_z=bias),
                    SplinedSourceWindow(dlog10Ndm=0, zarr=z, W=nz2, bias_z=bias)]


cp.set_for_lmax(l_max)
cp.SourceTerms.limber_windows = True
cp.SourceTerms.counts_redshift = False

cp.Want_CMB = False
cp.WantScalars = True
cp.WantDerivedParameters = False
cp.Want_CMB_lensing = False
cp.DoLensing = False
cp.Want_cl_2D_array = True

results = camb.get_results(cp)
cls = results.get_source_cls_dict()

print(cls.keys())
```

And instead of exception like 'unknown argument' it kills my kernel with this:
```

Error: Session cannot generate requests
Error: Session cannot generate requests
at w.executeCodeCell (/Users/sdbykov/.vscode/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension.js:90:327199)
at w.execute (/Users/sdbykov/.vscode/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension.js:90:326520)
at w.start (/Users/sdbykov/.vscode/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension.js:90:322336)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at t.CellExecutionQueue.executeQueuedCells (/Users/sdbykov/.vscode/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension.js:90:336863)
at t.CellExecutionQueue.start (/Users/sdbykov/.vscode/extensions/ms-toolsai.jupyter-2021.8.1236758218/out/client/extension.js:90:336403)

```

I really spend an hour looking for the source of error. I thought that such typo would be indicated with an exception, but probably the wrong argument name creates problems before that.

Thanks.

**Comment by cmbant** [comment]
I've tried to add some more general attribute check in https://github.com/cmbant/CAMB/commit/0e9e56a1e56cf9c4c398a0389c4dc67b1d9a3751
