### ISSUE TITLE
ARM Mac issue

### ISSUE THREAD

**Issue by karlglazebrook** [cmbant/CAMB#145]
Hi there,

Ran in to an issue with trying to install and use this on an ARC Mac. 

`pip install camb` worked fine. v1.5.0

The problem arises when one imports it one gets a dynamic loading error:
```
>>> import camb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karl/anaconda3/lib/python3.8/site-packages/camb/__init__.py", line 12, in <module>
    from . import baseconfig
  File "/Users/karl/anaconda3/lib/python3.8/site-packages/camb/baseconfig.py", line 66, in <module>
    camblib = ctypes.LibraryLoader(IfortGfortranLoader).LoadLibrary(CAMBL)
  File "/Users/karl/anaconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)
  File "/Users/karl/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/karl/anaconda3/lib/python3.8/site-packages/camb/camblib.so, 0x0006): tried: '/Users/karl/anaconda3/lib/python3.8/site-packages/camb/camblib.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

This seems rather odd since the library built correctly and 'TesterRelease' in the fortran directory passes all tests.
 Something is checking for a wrong arch when it should not be?

Any help appreciated.

**Comment by cmbant** [comment]
It doesn't sound like a CAMB-specific issue. E.g. see
https://stackoverflow.com/questions/71882029/mach-o-file-but-is-an-incompatible-architecture-have-arm64-need-x86-64-i

**Comment by karlglazebrook** [comment]
Hmm yes I agree it is likely not a camb specific problem - unless there are some compiler flags that need changing? My experience is that fortran/C mixes are always unholy and now we have python to!

Maybe it Is a problem with dlopen in python or something about how anaconda is configured, or something else.

The solutions in the linked article (which is about Flutter) seem to involve ugly hacks - e.g. installing a second version of compiler tools using brew. (I do use brew but I try not to mix brew stuff with anaconda stuff!)

Anyway it is not clear if this is something you can solve, but more tests would be interesting. e.g. if someone was able to try this on different MacOS versions and python installations.
