### ISSUE TITLE
Error installing CAMB

### ISSUE THREAD

**Issue by jpbrandtu** [cmbant/CAMB#146]
When doing `pip install -e ./CAMB [--user]` I get the following error:

```
ERROR: Exception:
Traceback (most recent call last):
  File "//anaconda3/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 102, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "//anaconda3/lib/python3.9/site-packages/pip/_vendor/pyparsing/util.py", line 256, in _inner
    return fn(self, *args, **kwargs)
  File "//anaconda3/lib/python3.9/site-packages/pip/_vendor/pyparsing/core.py", line 1190, in parse_string
    raise exc.with_traceback(None)
pip._vendor.pyparsing.exceptions.ParseException: Expected string_end, found '['  (at char 11), (line:1, col:12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
    return func(self, options, args)
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 342, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 414, in get_requirements
    req_to_add = install_req_from_line(
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 395, in install_req_from_line
    parts = parse_req_from_line(name, line_source)
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 332, in parse_req_from_line
    extras = convert_extras(extras_as_string)
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 57, in convert_extras
    return get_requirement("placeholder" + extras.lower()).extras
  File "//anaconda3/lib/python3.9/site-packages/pip/_internal/utils/packaging.py", line 45, in get_requirement
    return Requirement(req_string)
  File "//anaconda3/lib/python3.9/site-packages/pip/_vendor/packaging/requirements.py", line 104, in __init__
    raise InvalidRequirement(
pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "'[--user]'": Expected string_end
```

**Comment by jpbrandtu** [comment]
I've solved the issue writing only `pip install -e ./CAMB`
