### ISSUE TITLE
Installing from pip fails at building the wheel for the package

### ISSUE THREAD

**Issue by deyanmihaylov** [cmbant/CAMB#155]
I am trying to install the package using
```
pip install camb
```
after which I get the following output and the installation fails:
```
Collecting camb
  Using cached camb-1.5.4.tar.gz (1.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy>=1.0 in /Users/deyanmihaylov/Documents/Work/pyenvs/python312/lib/python3.12/site-packages (from camb) (1.13.0)
Collecting sympy>=1.0 (from camb)
  Using cached sympy-1.12-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: packaging in /Users/deyanmihaylov/Documents/Work/pyenvs/python312/lib/python3.12/site-packages (from camb) (24.0)
Requirement already satisfied: numpy<2.3,>=1.22.4 in /Users/deyanmihaylov/Documents/Work/pyenvs/python312/lib/python3.12/site-packages (from scipy>=1.0->camb) (1.26.4)
Collecting mpmath>=0.19 (from sympy>=1.0->camb)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Building wheels for collected packages: camb
  Building wheel for camb (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for camb (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running bdist_wheel
      running build
      running build_py
      Traceback (most recent call last):
        File "/Users/deyanmihaylov/Documents/Work/pyenvs/python312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/deyanmihaylov/Documents/Work/pyenvs/python312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/deyanmihaylov/Documents/Work/pyenvs/python312/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 251, in <module>
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 104, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
          self.run_command(cmd_name)
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 967, in run_command
          super().run_command(command)
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-build-env-su931j6c/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 216, in run
        File "<string>", line 91, in make_library
        File "/private/var/folders/_9/tgq57xfn3wlddld6773mdtq00000gn/T/pip-install-q71_hugb/camb_6e994746d824414db8893f524200ee94/camb/_compilers.py", line 85, in check_gfortran
          raise Exception(
      Exception: You need ifort or gfortran 6 or higher to compile (found: None).
      See https://camb.readthedocs.io/en/latest/fortran_compilers.html
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for camb
Failed to build camb
ERROR: Could not build wheels for camb, which is required to install pyproject.toml-based projects
```
This is using `python3.12`, however this was tested also using `python3.10` and `python3.9` where the same issue (with a slightly differently worded error message) occurred.

**Comment by cmbant** [comment]
Is the error message not correct or helpful?

**Comment by deyanmihaylov** [comment]
I believe the error message to be incorrect since I had `gfortran` and it was in my path too. Uninstalling `gcc` and installing it from scratch fixed the issue and I was able to `pip install camb`. No idea why it was complaining before.
