### ISSUE TITLE
installation for Python3.x

### ISSUE THREAD

**Issue by mehdirezaie** [cmbant/CAMB#19]
Hi! I wanted to install the camb module for python. I ran into the following error. I was wondering if anyone had any idea of what is wrong? I would appreciate any help

* installtion using pip
```
>>>  pip install camb
 Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/x6/lpg6rn5n311cc8c97bg9nk9m0000gn/T/pip-build-89948bmt/camb/setup.py", line 124, in <module>
      keywords=['cosmology', 'CAMB']
    File "/Users/mehdi/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/mehdi/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/mehdi/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/Users/mehdi/anaconda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 232, in run
      self.distinfo_dir)
    File "/Users/mehdi/anaconda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 364, in egg2dist
      raise ValueError(err)
  ValueError: Egg metadata expected at build/bdist.macosx-10.7-x86_64/wheel/camb-0.1.5-py3.6.egg-info but not found
  
  ----------------------------------------
  Failed building wheel for camb
  Running setup.py clean for camb
Failed to build camb
Installing collected packages: camb
  Running setup.py install for camb ... error
    Complete output from command /Users/mehdi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x6/lpg6rn5n311cc8c97bg9nk9m0000gn/T/pip-build-89948bmt/camb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x6/lpg6rn5n311cc8c97bg9nk9m0000gn/T/pip-uc73eo7e-record/install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: option --single-version-externally-managed not recognized
    
    ----------------------------------------
Command "/Users/mehdi/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/x6/lpg6rn5n311cc8c97bg9nk9m0000gn/T/pip-build-89948bmt/camb/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/x6/lpg6rn5n311cc8c97bg9nk9m0000gn/T/pip-uc73eo7e-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/x6/lpg6rn5n311cc8c97bg9nk9m0000gn/T/pip-build-89948bmt/camb/
```

* installation using `python setup.py install --user`
```
aerimus:pycamb mehdi$ python setup.py install --user
running install
Compiling source...
Traceback (most recent call last):
  File "setup.py", line 136, in <module>
    keywords=['cosmology', 'CAMB']
  File "/Users/mehdi/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/mehdi/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/mehdi/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 98, in run
    if parse_version(gfortran_version) < parse_version('4.9'):
  File "/Users/mehdi/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 206, in parse_version
  File "/Users/mehdi/anaconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by cmbant** [comment]
For the first one you need --egg. However I think it probably still doesn't work probably at the moment, if you know how to fix it please let me know. (however the installation may work even if you get errors installing)

For the second one I pushed a fix, please let me know if it works for you.

**Comment by cmbant** [comment]
I think version 1.5.1.1 now also fixes the pip install issue, please check.

**Comment by mehdirezaie** [comment]
Thanks @cmbant so much! I just tried `pip` and it worked pretty well!

**Comment by ziwenkk** [comment]
@mehdirezaie How did you do that exactly? Is it working for python3?

**Comment by cmbant** [comment]
Version 1.x should be fully python 3 compatible. Please open a new issue if you have a specific problem.
