### ISSUE TITLE
WantTensors=True,  want_zstar=True causes error "binary_search (e.g for optical depth) did not converge"

### ISSUE THREAD

**Issue by joezuntz** [cmbant/CAMB#62]
Hi again,

Sorry for the issue flurry!

Running with both `WantTensors=True` and `want_zstar=True` at the same time seems to cause a binary_search error in `calc_transfers`.  Not sure if this is expected for some reason.

Here's an example:
```
import camb
import traceback

for tensors in [False, True]:
    for zstar in [False, True]:

        cp = camb.set_params(ns=1, H0=67, ombh2=0.022, omch2=0.1,
                             lmax=2600, kmax=10.0, dark_energy_model='DarkEnergyPPF', 
                             WantTensors=tensors,
                             want_zstar=zstar)
        try:
            r = camb.get_results(cp)
            print("WantTensors={} and want_zstar={} succeeded".format(tensors, zstar))
        except camb.CAMBError:
            print("WantTensors={} and want_zstar={} failed with this error:".format(tensors, zstar))
            traceback.print_exc()
```

prints:
```
WantTensors=False and want_zstar=False succeeded
WantTensors=False and want_zstar=True succeeded
WantTensors=True and want_zstar=False succeeded
WantTensors=True and want_zstar=True failed with this error:
Traceback (most recent call last):
  File "tensors.py", line 12, in <module>
    r = camb.get_results(cp)
  File "/usr/local/lib/python3.7/site-packages/camb/camb.py", line 40, in get_results
    res.calc_power_spectra(params)
  File "/usr/local/lib/python3.7/site-packages/camb/results.py", line 307, in calc_power_spectra
    self.calc_transfers(params, only_transfers=False)
  File "/usr/local/lib/python3.7/site-packages/camb/results.py", line 290, in calc_transfers
    config.check_global_error('calc_transfer')
  File "/usr/local/lib/python3.7/site-packages/camb/_config.py", line 49, in check_global_error
    raise CAMBError(reference + '%s' % err)
camb.baseconfig.CAMBError: Error in Fortran called from calc_transfer:
binary_search (e.g for optical depth) did not converge
```

**Comment by cmbant** [comment]
Try https://github.com/cmbant/CAMB/commit/8b66482cc4491028a78b4b57fd818b486c5a7441

**Comment by joezuntz** [comment]
Perfect fix - thanks v much!
