### ISSUE TITLE
[Python wrapper] help(camb) throws a RecursionError

### ISSUE THREAD

**Issue by JCGoran** [cmbant/CAMB#78]
I've installed the Python wrapper from this repo, and when I try to access the internal documentation, for instance via:
```bash
python3 -c 'import camb; help(camb)'
```
I get the following error:
```python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.7/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/lib/python3.7/pydoc.py", line 1900, in __call__
    self.help(request)
  File "/usr/lib/python3.7/pydoc.py", line 1959, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/lib/python3.7/pydoc.py", line 1679, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/lib/python3.7/pydoc.py", line 1672, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/lib/python3.7/pydoc.py", line 389, in document
    if inspect.ismodule(object): return self.docmodule(*args)
  File "/usr/lib/python3.7/pydoc.py", line 1199, in docmodule
    contents.append(self.docother(value, key, name, maxlen=70))
  File "/usr/lib/python3.7/pydoc.py", line 1433, in docother
    repr = self.repr(object)
  File "/usr/lib/python3.7/reprlib.py", line 52, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.7/pydoc.py", line 1058, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/camb/camb/_config.py", line 59, in __repr__
    s += '%s = %s\n' % (x, getattr(self, x))
  File "/camb/camb/_config.py", line 59, in __repr__
    s += '%s = %s\n' % (x, getattr(self, x))
  File "/camb/camb/_config.py", line 59, in __repr__
    s += '%s = %s\n' % (x, getattr(self, x))
  [Previous line repeated 324 more times]
  File "/camb/camb/_config.py", line 57, in __repr__
    for x in dir(self):
RecursionError: maximum recursion depth exceeded while calling a Python object
```
I've checked that the same thing happens on different machines.
CAMB version (as reported by the wrapper): `1.1.3`

**Comment by cmbant** [comment]
Thanks, should be fixed in https://github.com/cmbant/CAMB/commit/cee67cab4f1ff04e184e71f6c7b06a9bda64577d

**Comment by JCGoran** [comment]
That seemed to have done the trick, thanks for the quick response!
